version: "2.1"

# AS 20 - inject 500k/s 2.5M total - remote AS 30
# Single interface.
# - Wait for trigger that the BGP receiver [? chopps: has got them?]
# - Loop
#   - Send 250K DOWN from previous set
#   - Send 250K UP new prefixes (not sent previously).
#   - Wait for trigger that the BGP receiver [? chopps: has got them?]

services:
  st_1:
    image: bgptest
    environment:
      LOCALAS: 10
      MAXROUTES: 2500000
      PEERIP: fc00::30
      PEERAS: 30
      ROUTERID: 10.0.0.10
    command:
      - bash
      - -c
      - envsubst < /bgptest/conf/gobgp-conf.tpl > /tmp/gobgp-conf.yml;
        gobgpd -t yaml -f /tmp/gobgp-conf.yml
    networks:
      ebgpnet:
        ipv6_address: fc00::10
    volumes:
      - .:/bgptest

  # AS 30 - receive 500k/s 2.5M total
  bgput:
    image: bgptest
    environment:
      IPEERIP: fc00::31
      LOCALAS: 30
      PEER_FT_AS: 20
      PEER_FT_IP: fc00::20
      PEER_ST1_AS: 10
      PEER_ST1_IP: fc00::10
      PEER_ST2_AS: 11
      PEER_ST2_IP: fc00::11
      PEER_ST3_AS: 12
      PEER_ST3_IP: fc00::12
      PEER_TR_IP: fc01::31
      ROUTERID: 10.0.0.30
    command:
      - bash
      - -c
      - envsubst < /bgptest/conf/bird6-bgput.tpl > /etc/bird6.conf;
        bird6 -dc /etc/bird6.conf;
    volumes:
      - .:/bgptest
    networks:
      ebgpnet:
        ipv6_address: fc00::30
      ibgpnet:
        ipv6_address: fc01::30
  # AS 30 - receive 500k/s 2.5M total
  ibgp:
    image: bgptest
    environment:
      LOCALAS: 30
      PEER_UT_AS: 30
      PEER_UT_IP: fc01::30
      ROUTERID: 10.0.0.31
    command:
      - bash
      - -c
      - envsubst < /bgptest/conf/bird6-ibgp.tpl > /etc/bird6.conf;
        bird6 -dc /etc/bird6.conf;
    volumes:
      - .:/bgptest
    networks:
      ibgpnet:
        ipv6_address: fc01::31

networks:
  ebgpnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fc00::/64
  ibgpnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fc01::/64
