[global.config]
  as = 100
  router-id = "1.1.1.1"
  local-address-list = [ "192.168.1.35" ]
  port = 9001

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.2.35"
    peer-as = 237
  [neighbors.transport.config]
    passive-mode = true
    local-address = "192.168.1.35"
