version: "2.1"

# Must define these in the shell
# global:
#   environment:
#       PFX4: 10.1
#       PFX6: fc01:1
#       IMAGES_DIR:  /var/tftp/images
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN

  # AS 20 - inject 500k/s 2.5M total - remote AS 30
  # Single interface.
  # - Wait for trigger that the BGP receiver [? chopps: has got them?]
  # - Loop
  #   - Send 250K DOWN from previous set
  #   - Send 250K UP new prefixes (not sent previously).
  #   - Wait for trigger that the BGP receiver [? chopps: has got them?]

services:

  # AS 20 - inject 500k/s 2.5M total
  # ebgp:
  #   # sysctls:
  #   #   - net.ipv6.conf.all.disable_ipv6=1
  #   #   - net.ipv6.conf.all.forwarding=1
  #   #   - net.ipv6.conf.default.forwarding=1
  #   # cap_add:
  #   #   - NET_ADMIN
  #   #   - SYS_ADMIN
  #   image: bgptest
  #   # command: bgpsim -f /bgptest/bgpsim.conf -v
  #   # command: bash -c 'sbgp -a -v -o /bgptest/sbgp.out AS20 10.0.0.30 AS30'
  #   command: gobgpd -t yaml -f /bgptest/conf/gobgp6-ebgp.yml
  #   volumes:
  #     - .:/bgptest
  #   ports:
  #     - 5674:5674
  #   networks:
  #     ebgpnet:
  #       ipv4_address: 10.0.0.20
  #       ipv6_address: fc00::20

  # AS 30 - receive 500k/s 2.5M total
  bgput:
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=1
    #   - net.ipv6.conf.all.forwarding=1
    #   - net.ipv6.conf.default.forwarding=1
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    image: bgptest
    # command: gobgpd -t yaml -f /bgptest/conf/gobgp6-bgput.yml
    command: bash -c 'mkdir -p /run/bird && bird -dc /bgptest/conf/bird-bgput.conf'
    volumes:
      - .:/bgptest
    networks:
      ebgpnet:
        ipv4_address: 10.0.0.30
        ipv6_address: fc00::30
      ibgpnet:
        ipv4_address: 10.0.1.30
        ipv6_address: fc01::30
  # AS 30 - receive 500k/s 2.5M total
  ibgp:
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=1
    #   - net.ipv6.conf.all.forwarding=1
    #   - net.ipv6.conf.default.forwarding=1
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    image: bgptest
    # command: gobgpd -t yaml -f /bgptest/conf/gobgp6-ibgp.yml
    # command: sbgp -a -v -o /bgptest/sbgp-ibgp.out AS30 10.0.1.30 AS30
    command: bash -c 'mkdir -p /run/bird && bird -dc /bgptest/conf/bird-ibgp.conf'
    volumes:
      - .:/bgptest
    networks:
      ibgpnet:
        ipv4_address: 10.0.1.31
        ipv6_address: fc01::31

networks:
  ebgpnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.0.0/24
        - subnet: fc00::/64
  ibgpnet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.1.0/24
        - subnet: fc01::/64
